spring:
  application:
    name: springAIDemo
  ai:
    # 配置ollama
    ollama:
      base-url: http://localhost:11434
      chat:
        model: deepseek-r1:1.5b
    # 配置openAI
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: qwen-max-latest
#          stream-usage: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.138.89.145:3306/SpringAI?serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowPublicKeyRetrieval=true&allowMultiQueries=true&useServerPrepStmts=false
    username: root
    password: 190715zcy


logging:
  level:
    org.springframework.ai: debug
    cloud.ciky: debug