spring:
  application:
    name: springAIDemo
  ai:
    # 配置ollama
    ollama:
      base-url: http://localhost:11434
      chat:
        model: deepseek-r1:1.5b
    # 配置openAI
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      api-key: sk-b524350c94c644bdaba8a8c70f2aa358
      chat:
        options:
          model: deepseek-r1
          stream-usage: true