spring:
  application:
    name: springAIDemo
  ai:
    # 配置ollama
    ollama:
      base-url: http://localhost:11434
      chat:
        model: deepseek-r1:1.5b
    # 配置openAI
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: qwen-max-latest
#          stream-usage: true

logging:
  level:
    org.springframework.ai.chat.client.advisor: debug
    cloud.ciky: debug